#ifndef MESH_H
#define MESH_H
#include <vector>
#include "libmesh/elem.h"
#include "libmesh/face_tri3.h"
#include "libmesh/mesh.h"
#include "libmesh/mesh_generation.h"
#include "libmesh/mesh_tetgen_interface.h"
#include "libmesh/mesh_triangle_interface.h"
#include "libmesh/node.h"
#include "libmesh/serial_mesh.h"

//This in the tetrahedralisation of a sphere
//void tetrahedralise_sphere(libMesh::MeshBase& mesh, const libMesh::Parallel::Communicator& comm);
void tetrahedralise_sphere(libMesh::UnstructuredMesh& mesh, const libMesh::Parallel::Communicator& comm);

// Helper routine for tetrahedralize_domain().  Adds the points and elements
// of a convex hull generated by TetGen to the input mesh
void add_sphere_convex_hull_to_mesh(libMesh::MeshBase& mesh, libMesh::Real radius, unsigned int points_on_sphere);

unsigned int closest(std::vector<libMesh::Point> geom, libMesh::Point pt);
std::vector<libMesh::Point> get_water();

#endif
