 #include <iostream>

void mn01_004 (double* x, double* y, double* z, double* w);
void mn02_009 (double* x, double* y, double* z, double* w);
void mn03_016 (double* x, double* y, double* z, double* w);
void mn04_025 (double* x, double* y, double* z, double* w);
void mn05_036 (double* x, double* y, double* z, double* w);
void mn06_049 (double* x, double* y, double* z, double* w);
void mn07_064 (double* x, double* y, double* z, double* w);
void mn08_081 (double* x, double* y, double* z, double* w);
void mn09_100 (double* x, double* y, double* z, double* w);
void mn10_121 (double* x, double* y, double* z, double* w);
void mn11_144 (double* x, double* y, double* z, double* w);
void mn12_169 (double* x, double* y, double* z, double* w);
void mn13_196 (double* x, double* y, double* z, double* w);
void mn14_225 (double* x, double* y, double* z, double* w);
void mn15_256 (double* x, double* y, double* z, double* w);

void me01_004 (double* x, double* y, double* z, double* w);
void me02_009 (double* x, double* y, double* z, double* w);
void me03_016 (double* x, double* y, double* z, double* w);
void me04_025 (double* x, double* y, double* z, double* w);
void me05_036 (double* x, double* y, double* z, double* w);
void me06_049 (double* x, double* y, double* z, double* w);
void me07_064 (double* x, double* y, double* z, double* w);
void me08_081 (double* x, double* y, double* z, double* w);
void me09_100 (double* x, double* y, double* z, double* w);
void me10_121 (double* x, double* y, double* z, double* w);
void me11_144 (double* x, double* y, double* z, double* w);
void me12_169 (double* x, double* y, double* z, double* w);
void me13_196 (double* x, double* y, double* z, double* w);
void me14_225 (double* x, double* y, double* z, double* w);
void me15_256 (double* x, double* y, double* z, double* w);

void ev01_0004 (double* x, double* y, double* z, double* w);
void ev02_0009 (double* x, double* y, double* z, double* w);
void ev03_0016 (double* x, double* y, double* z, double* w);
void ev04_0025 (double* x, double* y, double* z, double* w);
void ev05_0036 (double* x, double* y, double* z, double* w);
void ev06_0049 (double* x, double* y, double* z, double* w);
void ev07_0064 (double* x, double* y, double* z, double* w);
void ev08_0081 (double* x, double* y, double* z, double* w);
void ev09_0100 (double* x, double* y, double* z, double* w);
void ev10_0121 (double* x, double* y, double* z, double* w);
void ev11_144 (double* x, double* y, double* z, double* w);
void ev12_169 (double* x, double* y, double* z, double* w);
void ev13_196 (double* x, double* y, double* z, double* w);
void ev14_225 (double* x, double* y, double* z, double* w);
void ev15_256 (double* x, double* y, double* z, double* w);

void md01_004 (double* x, double* y, double* z, double* w);
void md02_009 (double* x, double* y, double* z, double* w);
void md03_016 (double* x, double* y, double* z, double* w);
void md04_025 (double* x, double* y, double* z, double* w);
void md05_036 (double* x, double* y, double* z, double* w);
void md06_049 (double* x, double* y, double* z, double* w);
void md07_064 (double* x, double* y, double* z, double* w);
void md08_081 (double* x, double* y, double* z, double* w);
void md09_100 (double* x, double* y, double* z, double* w);
void md10_121 (double* x, double* y, double* z, double* w);
void md11_144 (double* x, double* y, double* z, double* w);
void md12_169 (double* x, double* y, double* z, double* w);
void md13_196 (double* x, double* y, double* z, double* w);
void md14_225 (double* x, double* y, double* z, double* w);
void md15_256 (double* x, double* y, double* z, double* w);

int Wom_precision_table( unsigned int approx_pts, int* exact_pts);
void Wom_points (int rule, unsigned int order, double* x, double* y, double* z, double* w);
bool unavailable(int rule);
int max_avail();
